openapi: 3.0.0
info:
  title: Quiz App API
  description: API for Question and Submit Applications
  version: 1.0.0
paths:
  /categories:
    get:
      summary: Get all categories
      responses:
        '200':
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /question/{category}:
    get:
      summary: Get a question by category
      parameters:
        - name: category
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A question for the specified category
          content:
            application/json:
              schema:
                type: object
                properties:
                  question:
                    type: string
                  answers:
                    type: array
                    items:
                      type: object
                      properties:
                        text:
                          type: string
                        isCorrect:
                          type: boolean
  /submit:
    post:
      summary: Submit a new question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                answers:
                  type: array
                  items:
                    type: object
                    properties:
                      text:
                        type: string
                      isCorrect:
                        type: boolean
                category:
                  type: string
      responses:
        '200':
          description: Question submitted successfully
